# =============================
# -=-=-=  MySQL Settings =-=-=-
# =============================
# MySQL Database
mysql:
    driver: com.mysql.jdbc.Driver
    host: jdbc:mysql://localhost
    username: root
    password: root
    database: minecraft_tournament

# =================================
# -=-=-= Bungeecord settings =-=-=-
# =================================

# Name of the server in the bungeecord configuration
server_name: null

# Name of the lobby server in the bungeecord configuration
lobby_server: lobby

# =============================
# -=-=-=  Score settings =-=-=-
# =============================

# Added on kill
kill_score_enabled: false
kill_score: 20

# Added on player placement
win_score_enabled: false
win_score: [100, 80, 60]


# Added when another player is eliminated
participation_score_enabled: false
participation_score: 2

# ==================================
# -=-=-= Player head settings =-=-=-
# ==================================

# Head drops
enable_head_drops: true

# Edible heads
enable_edible_heads: true

# ============================
# -=-=-= Lobby settings =-=-=-
# ============================

lobby_enabled: false

# Spawn location
spawn_x: 0.5
spawn_y: 10.0
spawn_z: 0.5

spawn_yaw: 0
spawn_pitch: 0

# KOTL
kotl_x: 25
kotl_z: 11

kotl_radius: 5

# Lobby leaderboard
lobby_player_leaderboard:
    x: 0.0
    y: 0.0
    z: 0.0

lobby_team_leaderboard:
    x: 0.0
    y: 0.0
    z: 0.0

# ===========================
# -=-=-= Game settings =-=-=-
# ===========================

game_enabled: false